apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-hello-world
  labels:
    app: spring-boot-hello-world
spec:
  selector:
    matchLabels:
      app: spring-boot-hello-world
  template:
    metadata:
      labels:
        app: spring-boot-hello-world
    spec:
      containers:
      - name: spring-boot-hello-world
        image: bobcrutchley/spring-boot-hello-world
        ports:
        - name: http-port
          containerPort: 8080
